version: "3.7"
services:
  server:
    image: cmd_server:production
    container_name: cmd_server
    build:
      args:
        - CONFIG_PATH=nginx_no_ssl
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cert:/usr/cert
    networks:
      - callmeduy

networks:
  callmeduy:
    name: callmeduy
    external: true
