version: "3"
services:
  webserver:
    ports:
      - "8000:8000"
    image: crccheck/hello-world

  nginx_issue:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx_issue:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot_issue:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx_issue
    command: renew --dry-run
      # certonly --webroot --webroot-path=/var/www/certbot --email trancongvietan22@gmail.com 
      # --agree-tos --no-eff-email --force-renewal -d www.rudias.asia

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot_renew:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: renew --dry-run
