version: "3.7"
services:
  nginx-dev:
    container_name: nginx
    image: nginx:1.7
    ports:
      - "80:80"
    volumes:
      - ./config/nginx_dev:/etc/nginx/conf.d
    networks:
      - rudias

networks:
  rudias:
    name: rudias
