version: "3.7"
services:
  server:
    image: nginx_reverse_proxy:no_ssl
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    #volumes:
      #- /etc/letsencrypt:/etc/letsencrypt
  service:
    image: crccheck/hello-world

    
