version: "3.7"
services:
  nginx-dev:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx_dev:/etc/nginx/conf.d
    networks: 
      - rudias-dev
networks: 
  rudias-dev:
    name: rudias-dev