version: "3.7"
services:
  server_dev:
    container_name: cmd-server:development
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx_no_ssl:/etc/nginx/conf.d
    networks:
      - callmeduy

networks:
  callmeduy:
    name: callmeduy
    external: true
