version: "3.7"
services:
  nginx:
    image: nginx:1.7-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
    networks:
      - rudias
  webserver:
    image: rudias-frontend:static
    container_name: webserver
    ports:
      - 8000:8000
    networks:
      rudias:
        aliases:
          - keystone

networks:
  rudias:
    name: rudias
