version: "3"
services:
  nginx_issue:
    image: nginx:1.7-alpine
    container_name: nginx_issue
    ports:
      - "80:80"
    volumes:
      - ./config/nginx_issue:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot

  certbot_issue:
    container_name: certbot_issue
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    depends_on:
      - nginx_issue
    command: >
      certonly --webroot --webroot-path=/var/www/certbot --email trancongvietan22@gmail.com 
      --agree-tos --no-eff-email --force-renew -d www.rudias.asia -d rudias.asia -d m.rudias.asia -d pwa.rudias.asia -d beta.rudias.asia

  certbot_renew:
    image: certbot/certbot
    container_name: certbot_renew
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    command: renew
