version: "3.7"
services:
  nginx:
    image: nginx:1.7-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx_staging:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
    networks:
      - rudias
  app:
    image: crccheck/hello-world
    container_name: test
    ports:
      - "8000:8000"
    networks:
      - rudias
networks:
  rudias:
    name: rudias
